### ISSUE TITLE
go get "submodule" error

### ISSUE THREAD

**Issue by markbates** [divan/gobenchui#3]
When trying to install, using the following command from the README:

```
$ go get -u github.com/divan/gobenchui
```

I get the following error:

```
# cd .; git --git-dir=$GOPATH/src/github.com/divan/gobenchui/.git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'example'
package github.com/divan/gobenchui: exit status 1
```

**Comment by divan** [comment]
That's weird. I have no idea why it may fail. 'example' is a submodule - because it contains own git history (it's exactly the purpose of example).
Can you provide more info, your git version, GOPATH?

**Comment by markbates** [comment]
I'm using GIT 2.6.1 and my GOPATH (not that it should matter) is /Users/markbates/Dropbox/development/gocode. 

Try deleting the project on your side and doing a go get on it and see what happens. It's pretty easy to reproduce.

**Comment by markbates** [comment]
Also using the following go:

go version go1.5.1 darwin/amd64

**Comment by divan** [comment]
> Try deleting the project on your side and doing a go get on it and see what happens. It's pretty easy to reproduce.
I did it before open-sourcing code, and just double-checked, deleted and go get again. Works for me and many other people. My guess is that it's something with your GOPATH (maybe you have .git folder in parent dirs or something like this?).

But not sure, need investigation. Basically, it's simple git project with one submodule, nothing else.

**Comment by divan** [comment]
Just got rid of this submodule (example/) completely.
