### ISSUE TITLE
Directory Symbolic Links cause error

### ISSUE THREAD

**Issue by boonep** [divan/gobenchui#9]
Error caused by a directory symbolic link in the project directory:

i.e.

/go/src/github.com/project/symbolic_link -> /home/me/directory

throws and error, because the walker reads the current file as a not directory, but then the CopyFile() function uses Stat() which reads the symbolic link target as a directory and throws an error.

```
Couldn't clone dir: dir argument to CopyFile (/tmp/gobenchui758924436/src/pkg/symbolic_link, /home/me/directory)
```

**Comment by divan** [comment]
Thanks! Applied PR.
